# Generated by Django 5.0.7 on 2024-07-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('listing_id', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
